module.exports = {
  accountUnconfirmed: 'Account unconfirmed',
  confirmToLogin: 'Please confirm your account to login.',
  emailAddress: 'Email Address',
  forgotPassword: 'Forgot Password?',
  invalidEmailAddress: 'Invalid email address',
  invalidPassword: 'Invalid password',
  login: 'Log in',
  loginWithFacebook: 'Log in with Facebook',
  noAccount: 'Don\'t have an account?',
  noConfirmation: 'Didn\'t receive any confirmation?',
  password: 'Password',
  signUp: 'Sign up',
  title: 'Log in to experience awesome',
};
