module.exports = {
  bySigningUp: 'Pinaagi sa Pag-sign Up miuyon kamo sa among',
  emailAddress: 'Email Address',
  errors: {
    'Email.Exists': 'Naa nay account nga nag-gamit ani nga Email Address.',
    'Email.Required': 'Kinahanglan ang Email Address',
    'FirstName.Required': 'Kinahanglan ang Pangalan',
    'LastName.Required': 'Kinahanglan ang Apelyido',
    'Password.Invalid': 'Ang Password kinahanglan lapas sa 6 characters',
    'Password.Required': 'Kinahanglan ang Password',
  },
  firstName: 'Pangalan',
  haveAnAccount: 'Naa nay account?',
  industryProfessional: 'Usa ako ka Landlord o lisensiyadong propesyonal',
  lastName: 'Apelyido',
  login: 'Pag-log In',
  ofUse: '.',
  password: 'Password',
  signUp: 'Pag-sign Up',
  signUpWithFacebook: 'Pag-sign up gamit ang Facebook',
  terms: 'Mga Termino ug mga Kondisyon',
  title: 'Zazzio - Pag Sign Up',
  wantLogin: 'Ganahan kang Mo-log In?',
};
