module.exports = {
  errors: {
    'Email.Exists': 'Ang Email Address na ito ay nauugnay na sa isang account.',
    'Email.Required': 'Kinakailangan ang Email Address',
    'FirstName.Required': 'Kinakailangan ang Pangalan',
    'LastName.Required': 'Kinakailangan ang Apelyido',
    'Password.Invalid': 'Ang Password ay dapat higit sa 6 na characters',
    'Password.Required': 'Kinakailangan ang Password',
  },
  bySigningUp: 'Sa pag-sign up sumasang-ayon ka sa aming',
  emailAddress: 'Email Address',
  firstName: 'Pangalan',
  haveAnAccount: 'Mayroon nang account?',
  industryProfessional: 'Ako ay may-ari o isang lisensiyadong propesyonal',
  lastName: 'Apelyido',
  login: 'Mag-log in',
  ofUse: '.',
  password: 'Password',
  signUp: 'Mag-sign up',
  signUpWithFacebook: 'Mag-sign up gamit ang Facebook',
  terms: 'Mga Patakaran at Kundisyon',
  title: 'Zazzio - Mag Sign Up',
  wantLogin: 'Gusto mo bang Mag-log In?',
};
