/* eslint-disable */
const countries =
[{
  'ISO2Code': 'AF',
  'ISO3Code': 'AFG',
  'name': 'Afghanistan',
  'callingCode': '93'
}, {
  'ISO2Code': 'AX',
  'ISO3Code': 'ALA',
  'name': 'Åland Islands',
  'callingCode': '358'
}, {
  'ISO2Code': 'AL',
  'ISO3Code': 'ALB',
  'name': 'Albania',
  'callingCode': '355'
}, {
  'ISO2Code': 'DZ',
  'ISO3Code': 'DZA',
  'name': 'Algeria',
  'callingCode': '213'
}, {
  'ISO2Code': 'AS',
  'ISO3Code': 'ASM',
  'name': 'American Samoa',
  'callingCode': '1684'
}, {
  'ISO2Code': 'AD',
  'ISO3Code': 'AND',
  'name': 'Andorra',
  'callingCode': '376'
}, {
  'ISO2Code': 'AO',
  'ISO3Code': 'AGO',
  'name': 'Angola',
  'callingCode': '244'
}, {
  'ISO2Code': 'AI',
  'ISO3Code': 'AIA',
  'name': 'Anguilla',
  'callingCode': '1264'
}, {
  'ISO2Code': 'AQ',
  'ISO3Code': 'ATA',
  'name': 'Antarctica'
}, {
  'ISO2Code': 'AG',
  'ISO3Code': 'ATG',
  'name': 'Antigua and Barbuda',
  'callingCode': '1268'
}, {
  'ISO2Code': 'AR',
  'ISO3Code': 'ARG',
  'name': 'Argentina',
  'callingCode': '54'
}, {
  'ISO2Code': 'AM',
  'ISO3Code': 'ARM',
  'name': 'Armenia',
  'callingCode': '374'
}, {
  'ISO2Code': 'AW',
  'ISO3Code': 'ABW',
  'name': 'Aruba',
  'callingCode': '297'
}, {
  'ISO2Code': 'AU',
  'ISO3Code': 'AUS',
  'name': 'Australia',
  'callingCode': '61'
}, {
  'ISO2Code': 'AT',
  'ISO3Code': 'AUT',
  'name': 'Austria',
  'callingCode': '43'
}, {
  'ISO2Code': 'AZ',
  'ISO3Code': 'AZE',
  'name': 'Azerbaijan',
  'callingCode': '994'
}, {
  'ISO2Code': 'BS',
  'ISO3Code': 'BHS',
  'name': 'The Bahamas',
  'callingCode': '1242'
}, {
  'ISO2Code': 'BH',
  'ISO3Code': 'BHR',
  'name': 'Bahrain',
  'callingCode': '973'
}, {
  'ISO2Code': 'BD',
  'ISO3Code': 'BGD',
  'name': 'Bangladesh',
  'callingCode': '880'
}, {
  'ISO2Code': 'BB',
  'ISO3Code': 'BRB',
  'name': 'Barbados',
  'callingCode': '1246'
}, {
  'ISO2Code': 'BY',
  'ISO3Code': 'BLR',
  'name': 'Belarus',
  'callingCode': '375'
}, {
  'ISO2Code': 'BE',
  'ISO3Code': 'BEL',
  'name': 'Belgium',
  'callingCode': '32'
}, {
  'ISO2Code': 'BZ',
  'ISO3Code': 'BLZ',
  'name': 'Belize',
  'callingCode': '501'
}, {
  'ISO2Code': 'BJ',
  'ISO3Code': 'BEN',
  'name': 'Benin',
  'callingCode': '229'
}, {
  'ISO2Code': 'BM',
  'ISO3Code': 'BMU',
  'name': 'Bermuda',
  'callingCode': '1441'
}, {
  'ISO2Code': 'BT',
  'ISO3Code': 'BTN',
  'name': 'Bhutan',
  'callingCode': '975'
}, {
  'ISO2Code': 'BO',
  'ISO3Code': 'BOL',
  'name': 'Bolivia',
  'callingCode': '591'
}, {
  'ISO2Code': 'BQ',
  'ISO3Code': 'BES',
  'name': 'Bonaire',
  'callingCode': '5997'
}, {
  'ISO2Code': 'BA',
  'ISO3Code': 'BIH',
  'name': 'Bosnia and Herzegovina',
  'callingCode': '387'
}, {
  'ISO2Code': 'BW',
  'ISO3Code': 'BWA',
  'name': 'Botswana',
  'callingCode': '267'
}, {
  'ISO2Code': 'BR',
  'ISO3Code': 'BRA',
  'name': 'Brazil',
  'callingCode': '55'
}, {
  'ISO2Code': 'IO',
  'ISO3Code': 'IOT',
  'name': 'British Indian Ocean Territory',
  'callingCode': '246'
}, {
  'ISO2Code': 'VG',
  'ISO3Code': 'VGB',
  'name': 'Virgin Islands (British)',
  'callingCode': '1284'
}, {
  'ISO2Code': 'VI',
  'ISO3Code': 'VIR',
  'name': 'Virgin Islands (U.S.)',
  'callingCode': '1 340'
}, {
  'ISO2Code': 'BN',
  'ISO3Code': 'BRN',
  'name': 'Brunei',
  'callingCode': '673'
}, {
  'ISO2Code': 'BG',
  'ISO3Code': 'BGR',
  'name': 'Bulgaria',
  'callingCode': '359'
}, {
  'ISO2Code': 'BF',
  'ISO3Code': 'BFA',
  'name': 'Burkina Faso',
  'callingCode': '226'
}, {
  'ISO2Code': 'BI',
  'ISO3Code': 'BDI',
  'name': 'Burundi',
  'callingCode': '257'
}, {
  'ISO2Code': 'KH',
  'ISO3Code': 'KHM',
  'name': 'Cambodia',
  'callingCode': '855'
}, {
  'ISO2Code': 'CM',
  'ISO3Code': 'CMR',
  'name': 'Cameroon',
  'callingCode': '237'
}, {
  'ISO2Code': 'CA',
  'ISO3Code': 'CAN',
  'name': 'Canada',
  'callingCode': '1'
}, {
  'ISO2Code': 'CV',
  'ISO3Code': 'CPV',
  'name': 'Cape Verde',
  'callingCode': '238'
}, {
  'ISO2Code': 'KY',
  'ISO3Code': 'CYM',
  'name': 'Cayman Islands',
  'callingCode': '1345'
}, {
  'ISO2Code': 'CF',
  'ISO3Code': 'CAF',
  'name': 'Central African Republic',
  'callingCode': '236'
}, {
  'ISO2Code': 'TD',
  'ISO3Code': 'TCD',
  'name': 'Chad',
  'callingCode': '235'
}, {
  'ISO2Code': 'CL',
  'ISO3Code': 'CHL',
  'name': 'Chile',
  'callingCode': '56'
}, {
  'ISO2Code': 'CN',
  'ISO3Code': 'CHN',
  'name': 'China',
  'callingCode': '86'
}, {
  'ISO2Code': 'CX',
  'ISO3Code': 'CXR',
  'name': 'Christmas Island',
  'callingCode': '61'
}, {
  'ISO2Code': 'CC',
  'ISO3Code': 'CCK',
  'name': 'Cocos (Keeling) Islands',
  'callingCode': '61'
}, {
  'ISO2Code': 'CO',
  'ISO3Code': 'COL',
  'name': 'Colombia',
  'callingCode': '57'
}, {
  'ISO2Code': 'KM',
  'ISO3Code': 'COM',
  'name': 'Comoros',
  'callingCode': '269'
}, {
  'ISO2Code': 'CG',
  'ISO3Code': 'COG',
  'name': 'Republic of the Congo',
  'callingCode': '242'
}, {
  'ISO2Code': 'CD',
  'ISO3Code': 'COD',
  'name': 'Democratic Republic of the Congo',
  'callingCode': '243'
}, {
  'ISO2Code': 'CK',
  'ISO3Code': 'COK',
  'name': 'Cook Islands',
  'callingCode': '682'
}, {
  'ISO2Code': 'CR',
  'ISO3Code': 'CRI',
  'name': 'Costa Rica',
  'callingCode': '506'
}, {
  'ISO2Code': 'HR',
  'ISO3Code': 'HRV',
  'name': 'Croatia',
  'callingCode': '385'
}, {
  'ISO2Code': 'CU',
  'ISO3Code': 'CUB',
  'name': 'Cuba',
  'callingCode': '53'
}, {
  'ISO2Code': 'CW',
  'ISO3Code': 'CUW',
  'name': 'Curaçao',
  'callingCode': '5999'
}, {
  'ISO2Code': 'CY',
  'ISO3Code': 'CYP',
  'name': 'Cyprus',
  'callingCode': '357'
}, {
  'ISO2Code': 'CZ',
  'ISO3Code': 'CZE',
  'name': 'Czech Republic',
  'callingCode': '420'
}, {
  'ISO2Code': 'DK',
  'ISO3Code': 'DNK',
  'name': 'Denmark',
  'callingCode': '45'
}, {
  'ISO2Code': 'DJ',
  'ISO3Code': 'DJI',
  'name': 'Djibouti',
  'callingCode': '253'
}, {
  'ISO2Code': 'DM',
  'ISO3Code': 'DMA',
  'name': 'Dominica',
  'callingCode': '1767'
}, {
  'ISO2Code': 'DO',
  'ISO3Code': 'DOM',
  'name': 'Dominican Republic',
  'callingCode': '1809'
}, {
  'ISO2Code': 'EC',
  'ISO3Code': 'ECU',
  'name': 'Ecuador',
  'callingCode': '593'
}, {
  'ISO2Code': 'EG',
  'ISO3Code': 'EGY',
  'name': 'Egypt',
  'callingCode': '20'
}, {
  'ISO2Code': 'SV',
  'ISO3Code': 'SLV',
  'name': 'El Salvador',
  'callingCode': '503'
}, {
  'ISO2Code': 'GQ',
  'ISO3Code': 'GNQ',
  'name': 'Equatorial Guinea',
  'callingCode': '240'
}, {
  'ISO2Code': 'ER',
  'ISO3Code': 'ERI',
  'name': 'Eritrea',
  'callingCode': '291'
}, {
  'ISO2Code': 'EE',
  'ISO3Code': 'EST',
  'name': 'Estonia',
  'callingCode': '372'
}, {
  'ISO2Code': 'ET',
  'ISO3Code': 'ETH',
  'name': 'Ethiopia',
  'callingCode': '251'
}, {
  'ISO2Code': 'FK',
  'ISO3Code': 'FLK',
  'name': 'Falkland Islands',
  'callingCode': '500'
}, {
  'ISO2Code': 'FO',
  'ISO3Code': 'FRO',
  'name': 'Faroe Islands',
  'callingCode': '298'
}, {
  'ISO2Code': 'FJ',
  'ISO3Code': 'FJI',
  'name': 'Fiji',
  'callingCode': '679'
}, {
  'ISO2Code': 'FI',
  'ISO3Code': 'FIN',
  'name': 'Finland',
  'callingCode': '358'
}, {
  'ISO2Code': 'FR',
  'ISO3Code': 'FRA',
  'name': 'France',
  'callingCode': '33'
}, {
  'ISO2Code': 'GF',
  'ISO3Code': 'GUF',
  'name': 'French Guiana',
  'callingCode': '594'
}, {
  'ISO2Code': 'PF',
  'ISO3Code': 'PYF',
  'name': 'French Polynesia',
  'callingCode': '689'
}, {
  'ISO2Code': 'GA',
  'ISO3Code': 'GAB',
  'name': 'Gabon',
  'callingCode': '241'
}, {
  'ISO2Code': 'GM',
  'ISO3Code': 'GMB',
  'name': 'The Gambia',
  'callingCode': '220'
}, {
  'ISO2Code': 'GE',
  'ISO3Code': 'GEO',
  'name': 'Georgia',
  'callingCode': '995'
}, {
  'ISO2Code': 'DE',
  'ISO3Code': 'DEU',
  'name': 'Germany',
  'callingCode': '49'
}, {
  'ISO2Code': 'GH',
  'ISO3Code': 'GHA',
  'name': 'Ghana',
  'callingCode': '233'
}, {
  'ISO2Code': 'GI',
  'ISO3Code': 'GIB',
  'name': 'Gibraltar',
  'callingCode': '350'
}, {
  'ISO2Code': 'GR',
  'ISO3Code': 'GRC',
  'name': 'Greece',
  'callingCode': '30'
}, {
  'ISO2Code': 'GL',
  'ISO3Code': 'GRL',
  'name': 'Greenland',
  'callingCode': '299'
}, {
  'ISO2Code': 'GD',
  'ISO3Code': 'GRD',
  'name': 'Grenada',
  'callingCode': '1473'
}, {
  'ISO2Code': 'GP',
  'ISO3Code': 'GLP',
  'name': 'Guadeloupe',
  'callingCode': '590'
}, {
  'ISO2Code': 'GU',
  'ISO3Code': 'GUM',
  'name': 'Guam',
  'callingCode': '1671'
}, {
  'ISO2Code': 'GT',
  'ISO3Code': 'GTM',
  'name': 'Guatemala',
  'callingCode': '502'
}, {
  'ISO2Code': 'GG',
  'ISO3Code': 'GGY',
  'name': 'Guernsey',
  'callingCode': '44'
}, {
  'ISO2Code': 'GN',
  'ISO3Code': 'GIN',
  'name': 'Guinea',
  'callingCode': '224'
}, {
  'ISO2Code': 'GW',
  'ISO3Code': 'GNB',
  'name': 'Guinea-Bissau',
  'callingCode': '245'
}, {
  'ISO2Code': 'GY',
  'ISO3Code': 'GUY',
  'name': 'Guyana',
  'callingCode': '592'
}, {
  'ISO2Code': 'HT',
  'ISO3Code': 'HTI',
  'name': 'Haiti',
  'callingCode': '509'
}, {
  'ISO2Code': 'VA',
  'ISO3Code': 'VAT',
  'name': 'Holy See',
  'callingCode': '379'
}, {
  'ISO2Code': 'HN',
  'ISO3Code': 'HND',
  'name': 'Honduras',
  'callingCode': '504'
}, {
  'ISO2Code': 'HK',
  'ISO3Code': 'HKG',
  'name': 'Hong Kong',
  'callingCode': '852'
}, {
  'ISO2Code': 'HU',
  'ISO3Code': 'HUN',
  'name': 'Hungary',
  'callingCode': '36'
}, {
  'ISO2Code': 'IS',
  'ISO3Code': 'ISL',
  'name': 'Iceland',
  'callingCode': '354'
}, {
  'ISO2Code': 'IN',
  'ISO3Code': 'IND',
  'name': 'India',
  'callingCode': '91'
}, {
  'ISO2Code': 'ID',
  'ISO3Code': 'IDN',
  'name': 'Indonesia',
  'callingCode': '62'
}, {
  'ISO2Code': 'CI',
  'ISO3Code': 'CIV',
  'name': 'Ivory Coast',
  'callingCode': '225'
}, {
  'ISO2Code': 'IR',
  'ISO3Code': 'IRN',
  'name': 'Iran',
  'callingCode': '98'
}, {
  'ISO2Code': 'IQ',
  'ISO3Code': 'IRQ',
  'name': 'Iraq',
  'callingCode': '964'
}, {
  'ISO2Code': 'IE',
  'ISO3Code': 'IRL',
  'name': 'Republic of Ireland',
  'callingCode': '353'
}, {
  'ISO2Code': 'IM',
  'ISO3Code': 'IMN',
  'name': 'Isle of Man',
  'callingCode': '44'
}, {
  'ISO2Code': 'IL',
  'ISO3Code': 'ISR',
  'name': 'Israel',
  'callingCode': '972'
}, {
  'ISO2Code': 'IT',
  'ISO3Code': 'ITA',
  'name': 'Italy',
  'callingCode': '39'
}, {
  'ISO2Code': 'JM',
  'ISO3Code': 'JAM',
  'name': 'Jamaica',
  'callingCode': '1876'
}, {
  'ISO2Code': 'JP',
  'ISO3Code': 'JPN',
  'name': 'Japan',
  'callingCode': '81'
}, {
  'ISO2Code': 'JE',
  'ISO3Code': 'JEY',
  'name': 'Jersey',
  'callingCode': '44'
}, {
  'ISO2Code': 'JO',
  'ISO3Code': 'JOR',
  'name': 'Jordan',
  'callingCode': '962'
}, {
  'ISO2Code': 'KZ',
  'ISO3Code': 'KAZ',
  'name': 'Kazakhstan',
  'callingCode': '76'
}, {
  'ISO2Code': 'KE',
  'ISO3Code': 'KEN',
  'name': 'Kenya',
  'callingCode': '254'
}, {
  'ISO2Code': 'KI',
  'ISO3Code': 'KIR',
  'name': 'Kiribati',
  'callingCode': '686'
}, {
  'ISO2Code': 'KW',
  'ISO3Code': 'KWT',
  'name': 'Kuwait',
  'callingCode': '965'
}, {
  'ISO2Code': 'KG',
  'ISO3Code': 'KGZ',
  'name': 'Kyrgyzstan',
  'callingCode': '996'
}, {
  'ISO2Code': 'LA',
  'ISO3Code': 'LAO',
  'name': 'Laos',
  'callingCode': '856'
}, {
  'ISO2Code': 'LV',
  'ISO3Code': 'LVA',
  'name': 'Latvia',
  'callingCode': '371'
}, {
  'ISO2Code': 'LB',
  'ISO3Code': 'LBN',
  'name': 'Lebanon',
  'callingCode': '961'
}, {
  'ISO2Code': 'LS',
  'ISO3Code': 'LSO',
  'name': 'Lesotho',
  'callingCode': '266'
}, {
  'ISO2Code': 'LR',
  'ISO3Code': 'LBR',
  'name': 'Liberia',
  'callingCode': '231'
}, {
  'ISO2Code': 'LY',
  'ISO3Code': 'LBY',
  'name': 'Libya',
  'callingCode': '218'
}, {
  'ISO2Code': 'LI',
  'ISO3Code': 'LIE',
  'name': 'Liechtenstein',
  'callingCode': '423'
}, {
  'ISO2Code': 'LT',
  'ISO3Code': 'LTU',
  'name': 'Lithuania',
  'callingCode': '370'
}, {
  'ISO2Code': 'LU',
  'ISO3Code': 'LUX',
  'name': 'Luxembourg',
  'callingCode': '352'
}, {
  'ISO2Code': 'MO',
  'ISO3Code': 'MAC',
  'name': 'Macau',
  'callingCode': '853'
}, {
  'ISO2Code': 'MK',
  'ISO3Code': 'MKD',
  'name': 'Republic of Macedonia',
  'callingCode': '389'
}, {
  'ISO2Code': 'MG',
  'ISO3Code': 'MDG',
  'name': 'Madagascar',
  'callingCode': '261'
}, {
  'ISO2Code': 'MW',
  'ISO3Code': 'MWI',
  'name': 'Malawi',
  'callingCode': '265'
}, {
  'ISO2Code': 'MY',
  'ISO3Code': 'MYS',
  'name': 'Malaysia',
  'callingCode': '60'
}, {
  'ISO2Code': 'MV',
  'ISO3Code': 'MDV',
  'name': 'Maldives',
  'callingCode': '960'
}, {
  'ISO2Code': 'ML',
  'ISO3Code': 'MLI',
  'name': 'Mali',
  'callingCode': '223'
}, {
  'ISO2Code': 'MT',
  'ISO3Code': 'MLT',
  'name': 'Malta',
  'callingCode': '356'
}, {
  'ISO2Code': 'MH',
  'ISO3Code': 'MHL',
  'name': 'Marshall Islands',
  'callingCode': '692'
}, {
  'ISO2Code': 'MQ',
  'ISO3Code': 'MTQ',
  'name': 'Martinique',
  'callingCode': '596'
}, {
  'ISO2Code': 'MR',
  'ISO3Code': 'MRT',
  'name': 'Mauritania',
  'callingCode': '222'
}, {
  'ISO2Code': 'MU',
  'ISO3Code': 'MUS',
  'name': 'Mauritius',
  'callingCode': '230'
}, {
  'ISO2Code': 'YT',
  'ISO3Code': 'MYT',
  'name': 'Mayotte',
  'callingCode': '262'
}, {
  'ISO2Code': 'MX',
  'ISO3Code': 'MEX',
  'name': 'Mexico',
  'callingCode': '52'
}, {
  'ISO2Code': 'FM',
  'ISO3Code': 'FSM',
  'name': 'Federated States of Micronesia',
  'callingCode': '691'
}, {
  'ISO2Code': 'MD',
  'ISO3Code': 'MDA',
  'name': 'Moldova',
  'callingCode': '373'
}, {
  'ISO2Code': 'MC',
  'ISO3Code': 'MCO',
  'name': 'Monaco',
  'callingCode': '377'
}, {
  'ISO2Code': 'MN',
  'ISO3Code': 'MNG',
  'name': 'Mongolia',
  'callingCode': '976'
}, {
  'ISO2Code': 'ME',
  'ISO3Code': 'MNE',
  'name': 'Montenegro',
  'callingCode': '382'
}, {
  'ISO2Code': 'MS',
  'ISO3Code': 'MSR',
  'name': 'Montserrat',
  'callingCode': '1664'
}, {
  'ISO2Code': 'MA',
  'ISO3Code': 'MAR',
  'name': 'Morocco',
  'callingCode': '212'
}, {
  'ISO2Code': 'MZ',
  'ISO3Code': 'MOZ',
  'name': 'Mozambique',
  'callingCode': '258'
}, {
  'ISO2Code': 'MM',
  'ISO3Code': 'MMR',
  'name': 'Myanmar',
  'callingCode': '95'
}, {
  'ISO2Code': 'NA',
  'ISO3Code': 'NAM',
  'name': 'Namibia',
  'callingCode': '264'
}, {
  'ISO2Code': 'NR',
  'ISO3Code': 'NRU',
  'name': 'Nauru',
  'callingCode': '674'
}, {
  'ISO2Code': 'NP',
  'ISO3Code': 'NPL',
  'name': 'Nepal',
  'callingCode': '977'
}, {
  'ISO2Code': 'NL',
  'ISO3Code': 'NLD',
  'name': 'Netherlands',
  'callingCode': '31'
}, {
  'ISO2Code': 'NC',
  'ISO3Code': 'NCL',
  'name': 'New Caledonia',
  'callingCode': '687'
}, {
  'ISO2Code': 'NZ',
  'ISO3Code': 'NZL',
  'name': 'New Zealand',
  'callingCode': '64'
}, {
  'ISO2Code': 'NI',
  'ISO3Code': 'NIC',
  'name': 'Nicaragua',
  'callingCode': '505'
}, {
  'ISO2Code': 'NE',
  'ISO3Code': 'NER',
  'name': 'Niger',
  'callingCode': '227'
}, {
  'ISO2Code': 'NG',
  'ISO3Code': 'NGA',
  'name': 'Nigeria',
  'callingCode': '234'
}, {
  'ISO2Code': 'NU',
  'ISO3Code': 'NIU',
  'name': 'Niue',
  'callingCode': '683'
}, {
  'ISO2Code': 'NF',
  'ISO3Code': 'NFK',
  'name': 'Norfolk Island',
  'callingCode': '672'
}, {
  'ISO2Code': 'KP',
  'ISO3Code': 'PRK',
  'name': 'North Korea',
  'callingCode': '850'
}, {
  'ISO2Code': 'MP',
  'ISO3Code': 'MNP',
  'name': 'Northern Mariana Islands',
  'callingCode': '1670'
}, {
  'ISO2Code': 'NO',
  'ISO3Code': 'NOR',
  'name': 'Norway',
  'callingCode': '47'
}, {
  'ISO2Code': 'OM',
  'ISO3Code': 'OMN',
  'name': 'Oman',
  'callingCode': '968'
}, {
  'ISO2Code': 'PK',
  'ISO3Code': 'PAK',
  'name': 'Pakistan',
  'callingCode': '92'
}, {
  'ISO2Code': 'PW',
  'ISO3Code': 'PLW',
  'name': 'Palau',
  'callingCode': '680'
}, {
  'ISO2Code': 'PS',
  'ISO3Code': 'PSE',
  'name': 'Palestine',
  'callingCode': '970'
}, {
  'ISO2Code': 'PA',
  'ISO3Code': 'PAN',
  'name': 'Panama',
  'callingCode': '507'
}, {
  'ISO2Code': 'PG',
  'ISO3Code': 'PNG',
  'name': 'Papua New Guinea',
  'callingCode': '675'
}, {
  'ISO2Code': 'PY',
  'ISO3Code': 'PRY',
  'name': 'Paraguay',
  'callingCode': '595'
}, {
  'ISO2Code': 'PE',
  'ISO3Code': 'PER',
  'name': 'Peru',
  'callingCode': '51'
}, {
  'ISO2Code': 'PH',
  'ISO3Code': 'PHL',
  'name': 'Philippines',
  'callingCode': '63'
}, {
  'ISO2Code': 'PN',
  'ISO3Code': 'PCN',
  'name': 'Pitcairn Islands',
  'callingCode': '64'
}, {
  'ISO2Code': 'PL',
  'ISO3Code': 'POL',
  'name': 'Poland',
  'callingCode': '48'
}, {
  'ISO2Code': 'PT',
  'ISO3Code': 'PRT',
  'name': 'Portugal',
  'callingCode': '351'
}, {
  'ISO2Code': 'PR',
  'ISO3Code': 'PRI',
  'name': 'Puerto Rico',
  'callingCode': '1787'
}, {
  'ISO2Code': 'QA',
  'ISO3Code': 'QAT',
  'name': 'Qatar',
  'callingCode': '974'
}, {
  'ISO2Code': 'XK',
  'ISO3Code': 'KOS',
  'name': 'Republic of Kosovo',
  'callingCode': '383'
}, {
  'ISO2Code': 'RE',
  'ISO3Code': 'REU',
  'name': 'Réunion',
  'callingCode': '262'
}, {
  'ISO2Code': 'RO',
  'ISO3Code': 'ROU',
  'name': 'Romania',
  'callingCode': '40'
}, {
  'ISO2Code': 'RU',
  'ISO3Code': 'RUS',
  'name': 'Russia',
  'callingCode': '7'
}, {
  'ISO2Code': 'RW',
  'ISO3Code': 'RWA',
  'name': 'Rwanda',
  'callingCode': '250'
}, {
  'ISO2Code': 'BL',
  'ISO3Code': 'BLM',
  'name': 'Saint Barthélemy',
  'callingCode': '590'
}, {
  'ISO2Code': 'SH',
  'ISO3Code': 'SHN',
  'name': 'Saint Helena',
  'callingCode': '290'
}, {
  'ISO2Code': 'KN',
  'ISO3Code': 'KNA',
  'name': 'Saint Kitts and Nevis',
  'callingCode': '1869'
}, {
  'ISO2Code': 'LC',
  'ISO3Code': 'LCA',
  'name': 'Saint Lucia',
  'callingCode': '1758'
}, {
  'ISO2Code': 'MF',
  'ISO3Code': 'MAF',
  'name': 'Saint Martin',
  'callingCode': '590'
}, {
  'ISO2Code': 'PM',
  'ISO3Code': 'SPM',
  'name': 'Saint Pierre and Miquelon',
  'callingCode': '508'
}, {
  'ISO2Code': 'VC',
  'ISO3Code': 'VCT',
  'name': 'Saint Vincent and the Grenadines',
  'callingCode': '1784'
}, {
  'ISO2Code': 'WS',
  'ISO3Code': 'WSM',
  'name': 'Samoa',
  'callingCode': '685'
}, {
  'ISO2Code': 'SM',
  'ISO3Code': 'SMR',
  'name': 'San Marino',
  'callingCode': '378'
}, {
  'ISO2Code': 'ST',
  'ISO3Code': 'STP',
  'name': 'São Tomé and Príncipe',
  'callingCode': '239'
}, {
  'ISO2Code': 'SA',
  'ISO3Code': 'SAU',
  'name': 'Saudi Arabia',
  'callingCode': '966'
}, {
  'ISO2Code': 'SN',
  'ISO3Code': 'SEN',
  'name': 'Senegal',
  'callingCode': '221'
}, {
  'ISO2Code': 'RS',
  'ISO3Code': 'SRB',
  'name': 'Serbia',
  'callingCode': '381'
}, {
  'ISO2Code': 'SC',
  'ISO3Code': 'SYC',
  'name': 'Seychelles',
  'callingCode': '248'
}, {
  'ISO2Code': 'SL',
  'ISO3Code': 'SLE',
  'name': 'Sierra Leone',
  'callingCode': '232'
}, {
  'ISO2Code': 'SG',
  'ISO3Code': 'SGP',
  'name': 'Singapore',
  'callingCode': '65'
}, {
  'ISO2Code': 'SX',
  'ISO3Code': 'SXM',
  'name': 'Sint Maarten',
  'callingCode': '1721'
}, {
  'ISO2Code': 'SK',
  'ISO3Code': 'SVK',
  'name': 'Slovakia',
  'callingCode': '421'
}, {
  'ISO2Code': 'SI',
  'ISO3Code': 'SVN',
  'name': 'Slovenia',
  'callingCode': '386'
}, {
  'ISO2Code': 'SB',
  'ISO3Code': 'SLB',
  'name': 'Solomon Islands',
  'callingCode': '677'
}, {
  'ISO2Code': 'SO',
  'ISO3Code': 'SOM',
  'name': 'Somalia',
  'callingCode': '252'
}, {
  'ISO2Code': 'ZA',
  'ISO3Code': 'ZAF',
  'name': 'South Africa',
  'callingCode': '27'
}, {
  'ISO2Code': 'GS',
  'ISO3Code': 'SGS',
  'name': 'South Georgia',
  'callingCode': '500'
}, {
  'ISO2Code': 'KR',
  'ISO3Code': 'KOR',
  'name': 'South Korea',
  'callingCode': '82'
}, {
  'ISO2Code': 'SS',
  'ISO3Code': 'SSD',
  'name': 'South Sudan',
  'callingCode': '211'
}, {
  'ISO2Code': 'ES',
  'ISO3Code': 'ESP',
  'name': 'Spain',
  'callingCode': '34'
}, {
  'ISO2Code': 'LK',
  'ISO3Code': 'LKA',
  'name': 'Sri Lanka',
  'callingCode': '94'
}, {
  'ISO2Code': 'SD',
  'ISO3Code': 'SDN',
  'name': 'Sudan',
  'callingCode': '249'
}, {
  'ISO2Code': 'SR',
  'ISO3Code': 'SUR',
  'name': 'Suriname',
  'callingCode': '597'
}, {
  'ISO2Code': 'SJ',
  'ISO3Code': 'SJM',
  'name': 'Svalbard and Jan Mayen',
  'callingCode': '4779'
}, {
  'ISO2Code': 'SZ',
  'ISO3Code': 'SWZ',
  'name': 'Swaziland',
  'callingCode': '268'
}, {
  'ISO2Code': 'SE',
  'ISO3Code': 'SWE',
  'name': 'Sweden',
  'callingCode': '46'
}, {
  'ISO2Code': 'CH',
  'ISO3Code': 'CHE',
  'name': 'Switzerland',
  'callingCode': '41'
}, {
  'ISO2Code': 'SY',
  'ISO3Code': 'SYR',
  'name': 'Syria',
  'callingCode': '963'
}, {
  'ISO2Code': 'TW',
  'ISO3Code': 'TWN',
  'name': 'Taiwan',
  'callingCode': '886'
}, {
  'ISO2Code': 'TJ',
  'ISO3Code': 'TJK',
  'name': 'Tajikistan',
  'callingCode': '992'
}, {
  'ISO2Code': 'TZ',
  'ISO3Code': 'TZA',
  'name': 'Tanzania',
  'callingCode': '255'
}, {
  'ISO2Code': 'TH',
  'ISO3Code': 'THA',
  'name': 'Thailand',
  'callingCode': '66'
}, {
  'ISO2Code': 'TL',
  'ISO3Code': 'TLS',
  'name': 'East Timor',
  'callingCode': '670'
}, {
  'ISO2Code': 'TG',
  'ISO3Code': 'TGO',
  'name': 'Togo',
  'callingCode': '228'
}, {
  'ISO2Code': 'TK',
  'ISO3Code': 'TKL',
  'name': 'Tokelau',
  'callingCode': '690'
}, {
  'ISO2Code': 'TO',
  'ISO3Code': 'TON',
  'name': 'Tonga',
  'callingCode': '676'
}, {
  'ISO2Code': 'TT',
  'ISO3Code': 'TTO',
  'name': 'Trinidad and Tobago',
  'callingCode': '1868'
}, {
  'ISO2Code': 'TN',
  'ISO3Code': 'TUN',
  'name': 'Tunisia',
  'callingCode': '216'
}, {
  'ISO2Code': 'TR',
  'ISO3Code': 'TUR',
  'name': 'Turkey',
  'callingCode': '90'
}, {
  'ISO2Code': 'TM',
  'ISO3Code': 'TKM',
  'name': 'Turkmenistan',
  'callingCode': '993'
}, {
  'ISO2Code': 'TC',
  'ISO3Code': 'TCA',
  'name': 'Turks and Caicos Islands',
  'callingCode': '1649'
}, {
  'ISO2Code': 'TV',
  'ISO3Code': 'TUV',
  'name': 'Tuvalu',
  'callingCode': '688'
}, {
  'ISO2Code': 'UG',
  'ISO3Code': 'UGA',
  'name': 'Uganda',
  'callingCode': '256'
}, {
  'ISO2Code': 'UA',
  'ISO3Code': 'UKR',
  'name': 'Ukraine',
  'callingCode': '380'
}, {
  'ISO2Code': 'AE',
  'ISO3Code': 'ARE',
  'name': 'United Arab Emirates',
  'callingCode': '971'
}, {
  'ISO2Code': 'GB',
  'ISO3Code': 'GBR',
  'name': 'United Kingdom',
  'callingCode': '44'
}, {
  'ISO2Code': 'US',
  'ISO3Code': 'USA',
  'name': 'United States',
  'callingCode': '1'
}, {
  'ISO2Code': 'UY',
  'ISO3Code': 'URY',
  'name': 'Uruguay',
  'callingCode': '598'
}, {
  'ISO2Code': 'UZ',
  'ISO3Code': 'UZB',
  'name': 'Uzbekistan',
  'callingCode': '998'
}, {
  'ISO2Code': 'VU',
  'ISO3Code': 'VUT',
  'name': 'Vanuatu',
  'callingCode': '678'
}, {
  'ISO2Code': 'VE',
  'ISO3Code': 'VEN',
  'name': 'Venezuela',
  'callingCode': '58'
}, {
  'ISO2Code': 'VN',
  'ISO3Code': 'VNM',
  'name': 'Vietnam',
  'callingCode': '84'
}, {
  'ISO2Code': 'WF',
  'ISO3Code': 'WLF',
  'name': 'Wallis and Futuna',
  'callingCode': '681'
}, {
  'ISO2Code': 'EH',
  'ISO3Code': 'ESH',
  'name': 'Western Sahara',
  'callingCode': '212'
}, {
  'ISO2Code': 'YE',
  'ISO3Code': 'YEM',
  'name': 'Yemen',
  'callingCode': '967'
}, {
  'ISO2Code': 'ZM',
  'ISO3Code': 'ZMB',
  'name': 'Zambia',
  'callingCode': '260'
}, {
  'ISO2Code': 'ZW',
  'ISO3Code': 'ZWE',
  'name': 'Zimbabwe',
  'callingCode': '263'
}];
/* eslint-enable */

export function getAll() {
  return countries.map(c => ({
    name: c.name,
    callingCode: c.callingCode,
  }));
}

export function getByISO2(code) {
  return countries.find(c => c.ISO2Code === code);
}

export function getByISO3(code) {
  return countries.find(c => c.ISO3Code === code);
}

export function getByName(name) {
  return countries.find(c => c.name === name);
}
